"""Initial schema migration

Revision ID: 2d907dc3a338
Revises: 
Create Date: 2026-06-19 15:09:55.949287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d907dc3a338'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.drop_table('student_resumes')
    op.drop_index(op.f('ix_student_profiles_roll_number'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.add_column('applications', sa.Column('resume_url', sa.String(length=500), nullable=True))
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'OFFERED', 'REJECTED', name='applicationstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('applications', 'updated_at')
    op.add_column('companies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('companies', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.alter_column('companies', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.create_foreign_key(None, 'companies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('companies', 'name')
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'created_at')
    op.add_column('jobs', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('salary', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('experience', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('jobs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('jobs', 'requirements',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'ctc')
    op.drop_column('jobs', 'eligibility_cgpa')
    op.drop_column('jobs', 'created_at')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('jobs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('eligibility_cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('ctc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('jobs', 'requirements',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('jobs', 'status')
    op.drop_column('jobs', 'experience')
    op.drop_column('jobs', 'salary')
    op.drop_column('jobs', 'category')
    op.add_column('companies', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.alter_column('companies', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'industry')
    op.drop_column('companies', 'company_name')
    op.drop_column('companies', 'user_id')
    op.add_column('applications', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('applications', 'applied_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'OFFERED', 'REJECTED', name='applicationstatus'),
               existing_nullable=False)
    op.drop_column('applications', 'resume_url')
    op.create_table('student_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('roll_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resume_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('student_profiles_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_profiles_pkey'))
    )
    op.create_index(op.f('ix_student_profiles_roll_number'), 'student_profiles', ['roll_number'], unique=True)
    op.create_table('student_resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('projects', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_style', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('student_resumes_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_resumes_pkey'))
    )
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
