"""add_company_is_approved

Revision ID: 5a014362e69b
Revises: 2dafdfb41771
Create Date: 2026-06-19 15:57:21.296668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a014362e69b'
down_revision: Union[str, Sequence[str], None] = '2dafdfb41771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS student_resumes CASCADE")
    op.execute("DROP TABLE IF EXISTS student_profiles CASCADE")
    
    # Add is_approved as nullable first, default to False, then set NOT NULL
    op.add_column('companies', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.execute("UPDATE companies SET is_approved = FALSE")
    op.alter_column('companies', 'is_approved', nullable=False)
    
    op.add_column('jobs', sa.Column('ctc', sa.Float(), nullable=True))
    
    # Add eligibility_cgpa as nullable first, default to 0.0, then set NOT NULL
    op.add_column('jobs', sa.Column('eligibility_cgpa', sa.Float(), nullable=True))
    op.execute("UPDATE jobs SET eligibility_cgpa = 0.0")
    op.alter_column('jobs', 'eligibility_cgpa', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'eligibility_cgpa')
    op.drop_column('jobs', 'ctc')
    op.drop_column('companies', 'is_approved')
    op.create_table('student_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('roll_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('skills', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resume_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('student_profiles_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_profiles_pkey'))
    )
    op.create_index(op.f('ix_student_profiles_roll_number'), 'student_profiles', ['roll_number'], unique=True)
    op.create_table('student_resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('education', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('projects', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('template_style', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('student_resumes_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_resumes_pkey'))
    )
    # ### end Alembic commands ###
