"""Add external jobs table

Revision ID: 641951e0ba60
Revises: 5a014362e69b
Create Date: 2026-06-20 22:04:35.000233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641951e0ba60'
down_revision: Union[str, Sequence[str], None] = '5a014362e69b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=False),
    sa.Column('source_api', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_jobs_external_id'), 'external_jobs', ['external_id'], unique=True)
    op.create_index(op.f('ix_external_jobs_id'), 'external_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_jobs_id'), table_name='external_jobs')
    op.drop_index(op.f('ix_external_jobs_external_id'), table_name='external_jobs')
    op.drop_table('external_jobs')
    # ### end Alembic commands ###
